services:
  - type: web
    name: 56-card-game
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:common && npm run build:server && npm run build:client
    startCommand: cd packages/game-server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4500
    autoDeploy: true
