export interface IGame {
  cards?: string[];
  droppedCards?: string[];
  dropCardPlayer?: string[];
  teamACards?: string[];
  teamBCards?: string[];
  tableCards?: string[];
  currentBet?: string;
  currentTurn?: string;
  gameScore?: string;
  currentBetPlayerId?: string;
  notification?: string | any;
  canStartGame?: boolean;
  showBotSelection?: boolean;
  yourTurn?: boolean;
  gameOver?: boolean;
  leftGame?: boolean;
  error?: string;
  currentPlayerId?: string;
  players?: string[];
  penalityCards?: string[];
  isConnected?: boolean;
  trumpSuit?: string;
  playerTrumpSuit?: { [playerId: string]: string };
  roundWinnerTeam?: string;
  finalBid?: number;
  biddingTeam?: string;
  biddingPlayer?: string;
  isGameComplete?: boolean;
  teamAScore?: number;
  teamBScore?: number;
  winnerMessage?: string;
  isPendingReconnection?: boolean;
  gamePaused?: boolean;
  gameCompleteData?: {
    biddingTeamAchievedBid: boolean;
    teamAPoints: number;
    teamBPoints: number;
    teamAScore: number;
    teamBScore: number;
    scoreResetOccurred: boolean;
  };
  gameMode?: 'create' | 'join' | null;
  gameIdToJoin?: string;
  isGameCreator?: boolean;
  sharedGameId?: string;
  showGameModeSelection?: boolean;
}
